blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed


app_name = 'blog'

urlpatterns = [
    # path('', views.PostListView.as_view(), name='post_list'),
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/',views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/',
         views.post_detail, name='post_detail'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/share',
         views.post_share, name='post_share'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/comment/',
         views.post_comment, name='post_comment'),
    path('latest/feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

mysite/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from blog.sitemaps import PostSitemap, TagSitemap


sitemaps = {
    'posts': PostSitemap,
    'tags': TagSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
]

blog/models.py
from django.db import models
from django.db.models.functions import Now
from django.utils import timezone
from django.utils.text import slugify 
from django.urls import reverse
from django.contrib.auth.models import User
from django.conf import settings
from taggit.managers import TaggableManager


# Our Custom Manager rather than the default manager => [objects]
class PublishedManager(models.Manager):
    # We have overridden this method by written 'Super().get_qyeryset()' to build a custom QuerySet that filters 
    # posts by their status and returns a successive QuerySet that only includes posts with the PUBLISHED status.
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)
 
 
class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250, unique=True, null=False)
    slug = models.SlugField(max_length=250, null=False, unique_for_date='publish')
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    # Another way is to set the default value using current date and time of the database server
    # publish = models.DateTimeField(db_default=Now())
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status, default=Status.DRAFT)
    

    # Managers
    objects = models.Manager()  # The default manager
    published = PublishedManager()  # Our custom manager
    tags = TaggableManager()  # 3rd party manager
    
        
    class Meta:
        # To specify different default manager
        # default_manager_name = published
        
        # Setting a custom name for the table or it will be appname_modelname(blog_post)
        # db_table = 'posts_table'
        
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]


    def save(self, *args, **kwargs):
        # Ensure slug is based on the title before saving
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)
  
        
    def get_absolute_url(self):
        return reverse("blog:post_detail",
                       args=[
                            self.publish.year,
                            self.publish.month,
                            self.publish.day,
                            self.slug
                        ])

    def __str__(self):
        return self.title
    

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]
        
    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog/forms.py
from django import forms
from .models import Comment


class SharePostForm(forms.Form):
    name = forms.CharField(max_length=25)
    from_email = forms.EmailField(label='Email')
    to_email = forms.EmailField(label='To')
    comments = forms.CharField(required=False, widget=forms.Textarea(attrs={
        'class': 'form-control',
        'placeholder': 'Comment here!',
        'rows': 2,
        'cols': 50
        }))


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']
        

class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
import smtplib
from django.db.models import Count, F
from django.shortcuts import render, get_object_or_404
from django.http import Http404, HttpResponseServerError
from django.views.generic import ListView
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from taggit.models import Tag
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity
from .models import Post
from.forms import SharePostForm, CommentForm, SearchForm

# Create your views here.

# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginate_by = 3
#     template_name = 'blog/post/list.html'


def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    # Pagination with 3 posts per page
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page', 1)
    try:
        page_posts = paginator.page(page_number)
    except EmptyPage:
        # If page_number is out of range deliver the last page of the results
        page_posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        # If page_number is not an integer deliver the first page
        page_posts = paginator.page(1)
    return render(request, 'blog/post/list.html', {'page_posts': page_posts, 'tag': tag})


def post_detail(request, year, month, day, slug):
    post = get_object_or_404(Post, status=Post.Status.PUBLISHED,
                            publish__year=year,
                            publish__month=month,
                            publish__day=day,
                            slug=slug)
    
    # The following Solution is similar to the previous solution which is more simple
    # try:
    #     post = Post.published.get(id=id)
    # except Post.DoesNotExist:
    #     raise Http404('No post found.')
    
    comments = post.comments.filter(active=True)
    form = CommentForm()
    
    # Retrieve objects by shared tags using similar_objects() manager method
    similar_objects = post.tags.similar_objects()
    
    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]
    
    return render(request, 'blog/post/detail.html', 
                    {'post': post, 'comments': comments, 'form': form,
                     'similar_posts': similar_posts, 'similar_objects': similar_objects})


@require_POST
def post_comment(request, year, month, day, slug):
    post = get_object_or_404(Post, status=Post.Status.PUBLISHED,
                            publish__year=year,
                            publish__month=month,
                            publish__day=day,
                            slug=slug)
    comment = None
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
        
    return render(request, 'blog/post/comment.html', {'post': post, 'form': form, 'comment': comment})
         
         
def post_share(request, year, month, day, slug):
    post = get_object_or_404(Post, status=Post.Status.PUBLISHED,
                            publish__year=year,
                            publish__month=month,
                            publish__day=day,
                            slug=slug)
    sent = False
    if request.method == 'POST':
        form = SharePostForm(request.POST or None)
        if form.is_valid():
            try:
                cd = form.cleaned_data
                post_url = request.build_absolute_uri(post.get_absolute_url())
                subject = f"{cd['name']} recommends you read {post.title}"
                message = f"Read {post.title} at {post_url}\n\n {cd['name']}\'s comments: {cd['comments']}"
                send_mail(subject, message, from_email=None, recipient_list=[cd['to_email']], fail_silently=False)
                sent = True
            except (smtplib.SMTPException, OSError):
                return HttpResponseServerError('An error occurred while sending the email.')
    else:
        form = SharePostForm()
        
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent':sent})


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    
    if 'query' in request.GET:
        form = SearchForm(request.GET)
    if form.is_valid():
        query = form.cleaned_data['query']
        # results = (
        #     Post.published.annotate(
        #         similarity=TrigramSimilarity('title', query),
        #     )
        #     .filter(similarity__gt=0.1)
        #     .order_by('-similarity')
        # )
        results = (
            Post.published.annotate(
                title_similarity=TrigramSimilarity('title', query),
                body_similarity=TrigramSimilarity('body', query),
            )
            .annotate(similarity=F('title_similarity') + F('body_similarity'))
            .filter(similarity__gt=0.1)
            .order_by('-similarity')
        )
        # search_vector = SearchVector('title', weight='A', config='english') + \
        #                 SearchVector('body', weight='B', config='english')
        # search_query = SearchQuery(query, config='english')
        # results = Post.published.annotate(search=search_vector,
        #                                 rank=SearchRank(search_vector, search_query)
        #                                 ).filter(rank__gte=0.3).order_by('-rank')
    
    return render(request, 'blog/post/search.html', {'form': form, 'query': query, 'results': results})

templates/blog/post/comment.html
{% extends "blog/base.html" %}
{% block title %}Add a comment{% endblock title %}
{% block content %}
    {% if comment %}
        <h2>Your comment has been added.</h2>
        <p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
    {% else %}
        {% include "blog/post/includes/comment_form.html" %}
    {% endif %}
{% endblock content %}

templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock title %}
{% block content %}
    <h1>{{ post.title }}</h1>
    {% if post.tags %}
        <p class="tags">
            Tags:
            {% for tag in post.tags.all %}
                <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name|lower }}</a>
                {% comment %} 
                    If Used to separate the tags by commas and if the tag is the last will not add comma
                {% endcomment %}
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
    {% endif %}
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|markdown }}
    <p>
        <a href="{% url 'blog:post_share' post.publish.year post.publish.month post.publish.day post.slug %}">
            Share this post
        </a>
    </p>
    {% if similar_posts %}
        <h2>Similar Posts</h2>
        {% for post in similar_posts %}
            <p><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></p>
        {% endfor %}
    {% endif %}
    {% comment %} {% if similar_objects %}
        <h2>Similar Objects</h2>
        {% for post in similar_objects %}
            <p><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></p>
        {% endfor %}
    {% endif %} {% endcomment %}
    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
                {{ comment.body|linebreaks }}
        </div>
        <hr/>
    {% empty %}
        <p>There are no comments.</p>
    {% endfor %}
    {% include "blog/post/includes/comment_form.html" %}
{% endblock content %}

templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}My Blog{% endblock title %}
{% block content %}
    <h1>My Blog</h1>
    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}
    {% for post in page_posts %}
        <h2>
            <a href="{{post.get_absolute_url}}">
                {{ post.title }}
            </a>
        </h2>
        {% if post.tags %}
            <p class="tags">
                Tags:
                {% for tag in post.tags.all %}
                    <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name|lower }}</a>
                    {% comment %} 
                        If Used to separate the tags by commas and if the tag is the last will not add comma
                    {% endcomment %}
                    {% if not forloop.last %}, {% endif %}
                {% endfor %}
            </p>
        {% endif %}
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body|markdown|truncatewords_html:30 }}
    {% endfor %}
    {% include "pagination.html" with page=page_posts %}
    {% comment %} In case of using Class Based View {% endcomment %}
    {% comment %} {% include 'pagination.html' with page=page_obj %} {% endcomment %}
{% endblock content %}

templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}Search{% endblock title %}
{% block content %}
    {% if query %}
        <h1>Posts containing "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
                Found {{ total_results }} result{{ total_results|pluralize }}
            {% endwith %}
        </h3>
        {% for post in results %}
            <h4>
                <a href="{{ post.get_absolute_url }}">
                    {{ post.title }}
                </a>
            </h4>
            {{ post.body|markdown|truncatewords_html:12 }}
        {% empty %}
            <p>There are no results matched with "{{query}}".</p>
        {% endfor %}
        <p><a href="{% url 'blog:post_search' %}">Search again</a></p>
    {% else %}
        <h1>Search for posts</h1>
        <form method="get">
            {{ form.as_p }}
            <input type="submit" value="Search">
        </form>
    {% endif %}
{% endblock content %}

templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Share a post{% endblock title %}
{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to_email }}.
        </p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock content %}