blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed


app_name = 'blog'

urlpatterns = [
    # path('', views.PostListView.as_view(), name='post_list'),
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/',views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/',
         views.post_detail, name='post_detail'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/share',
         views.post_share, name='post_share'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/comment/',
         views.post_comment, name='post_comment'),
    path('latest/feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

mysite/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from blog.sitemaps import PostSitemap, TagSitemap


sitemaps = {
    'posts': PostSitemap,
    'tags': TagSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
]

templates/blog/post/includes/comment_form.html
<h2>Add a new comment</h2>
<form action="{% url 'blog:post_comment' post.publish.year post.publish.month post.publish.day post.slug %}" method="POST">
    {% csrf_token %}
    <div class="left">
        {{ form.name.as_field_group }}
    </div>
    <div class="left">
        {{ form.email.as_field_group }}
    </div>
    {{ form.body.as_field_group }}
    <p><input type="submit" value="Add comment"></p>
</form>